version: '3'

services:
    lnx:
      image: chillfish8/lnx:0.9.0
      ports:
        - "8000:8000"
      volumes:
        - "${PWD}/index-data:/index"
      environment:
        - HOST="0.0.0.0"
        - RUNTIME_THREADS=6
        - DISABLE_ASNI_LOGS=true
        - LOG_LEVEL=info
